server:
  port: 8881

spring:
  application:
    name: cloud-config-server #必须要与远程文件的前缀名相同，如 cloud-config-server-dev,cloud-config-server-test
  cloud:
    config:
      label: master #指明远程仓库的分支
      profile: dev #dev开发环境配置文件 #test测试环境 #pro正式环境
      discovery:
        enabled: true #是否从配置中心读取文件
        serviceId: config-server #配置中心的servieId，即服务名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/