server:
  port: 8881

spring:
  application:
    name: cloud-config-server #必须要与远程文件的前缀名相同，如 cloud-config-server-dev,cloud-config-server-test
  cloud:
    config:
      label: master #指明远程仓库的分支
      profile: dev #dev开发环境配置文件 #test测试环境 #pro正式环境
      uri: http://localhost:8888/ #指明配置服务中心的网址